name: "Check Deadlinks"

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-deadlinks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check for dead links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --config ./lychee.toml
            "fern/pages/**/*.mdx"
            "fern/pages/**/*.md"
            "fern/snippets/**/*.mdx"
          fail: true
