name: "Fern Check"

on:
  pull_request:
    paths:
      - fern/**
  push:
    branches: 
      - main

jobs:
  fern-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install fern
        run: npm install -g fern-api
      - name: fern check
        run: fern check --warnings
