name: Publish Docs

on:
  push:
    branches:
      - main
    paths:
      - fern/**

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/heads/main') && github.run_number > 1 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install RUM Dependencies
        working-directory: ./datadog-rum
        run: npm install

      - name: Build DD RUM Client with secrets
        working-directory: ./datadog-rum
        env: 
          VITE_DATADOG_APP_ID: ${{ secrets.VITE_DATADOG_APP_ID }}
          VITE_DATADOG_CLIENT_TOKEN: ${{ secrets.VITE_DATADOG_CLIENT_TOKEN }}
        run: npm run build

      - name: Install Fern
        run: npm install -g fern-api

      - name: Publish Docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --docs --instance https://paradex.docs.buildwithfern.com
